spring.application.name=TekupPulse



spring.datasource.url=jdbc:mysql://localhost:3306/TekupPulse?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayoubgwadria@gmail.com
spring.mail.password=nhue lobm yuct wafl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8082
